### ISSUE TITLE
Missing required options fields

### ISSUE THREAD

**Issue by StanislavGoryachev** [ibm-cloud-docs/appid#357]
```
// mandatory option to be passed in if app not deployed on IBM Cloud
let options = [
    "oauthServerUrl": "https://us-south.appid.cloud.ibm.com/oauth/v4/d8438de6-c325-4956-ad34-abd49194affd",
]
```
The options seems to have been cut, there is a trailing `,` but no more fields. This results in a warning that required fields are missing and the endpoint always responds with unauthorised.

Solution:
```
// mandatory option to be passed in if app not deployed on IBM Cloud
let options = [
    "oauthServerUrl": "https://us-south.appid.cloud.ibm.com/oauth/v4/d8438de6-c325-4956-ad34-abd49194affd",
"tenantId": "d8438de6-c325-4956-ad34-abd49194affd",
"clientId": <client id here>
]
```

**Comment by smguilia** [comment]
Hi @StanislavGoryachev,

Just wanted to let you know that I've opened an issue internally and discussed your feedback with the development team. There are a few things that need to be worked out before the docs can be updated. Thank you for pointing the issue out. Please don't hesitate to reach out in the future with more feedback as it comes up. Because we're tracking it internally, I'm going to close this issue.
