### ISSUE TITLE
APP id popup is showing redirect_uri parameter error in IE End edge even its working in chrome

### ISSUE THREAD

**Issue by rk111** [ibm-cloud-docs/appid#363]
{"error":"invalid_request","error_description":"missing redirect_uri parameter"}

**Comment by smguilia** [comment]
Hi @rk111,

Thanks for letting us know. Because this sounds like it could be a bug with IE could you open a support ticket with more information for the development team? If you'd prefer to not open a ticket, you can also reach out directly to the development team on Slack.

How to get connected on Slack: https://www.ibm.com/cloud/blog/announcements/get-help-with-ibm-cloud-app-id-related-questions-on-slack

You can open a support ticket here: https://cloud.ibm.com/unifiedsupport/cases/form?type=AdvancedMobileAccess-d6aece47-d840-45b0-8ab9-ad15354deeea

I'm going to close this issue, but please feel free to reopen if you have questions about either of those options!
-Shawna
