### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by betoui** [ibm-cloud-docs/appid#369]
I follow the instructions for the containerised apps with Ingress on OpenShif. I manage to do everything but nothing happens on my app. I am not sure how to figure out what I am doing wrong or if I just need to restart a specific pod. I tried the Istio option as well and had the same result

**Comment by smguilia** [comment]
Hi @betoui,

You might find it helpful to [join our Slack channel](https://www.ibm.com/cloud/blog/announcements/get-help-with-ibm-cloud-app-id-related-questions-on-slack) to work directly with the development team. They’ll be able to evaluate what could have gone wrong. Then, if any doc updates are needed or if a specific troubleshooting case is found, we can work together to update the docs for future users so that they don't encounter the same issue. Thank you!

-Shawna
